title:              0xMayar
email:              mayar.hewdy@gmail.com
description:        Cyber Security Blog
author:             0xMayar
baseurl:            "/"
url:                "https://0xmayar.github.io"

# Social Profiles
github_username:   0xmayar 
linkedin_username: 0xmayar

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
